### ISSUE TITLE
license

### ISSUE THREAD

**Issue by bwbohl** [mattwildig/image-size-report-task#1]
Dear @mattwildig first of all, many thanks for this nice work!

Any chance you pick an open license and add the corresponding info to this repo? This would ease the reuse of your code ;-)

many thanks in advance.

**Comment by mattwildig** [comment]
I’m a bit surprised that anyone found this little thing to be of use, but pleased nonetheless.

I’ve picked the zero clause BSD licence for it, that should allow you to use it as you want.

**Comment by bwbohl** [comment]
thanks and thumbs up ;-)
